export const SET_IS_SIGN_IN = 'SET_IS_SIGN_IN';

export const SET_NICK_NAME = 'SET_NICK_NAME';

export const SET_RECIPE_SEARCH = 'SET_RECIPE_SEARCH';

export const SET_RECIPE_CATEGORY = 'SET_RECIPE_CATEGORY';

export const SET_SHARE_RECIPE_DATA = 'SET_SHARE_RECIPE_DATA';

export const SET_RECIPE_IMAGE_FILE = 'SET_RECIPE_IMAGE_FILE';

export const SET_STEP_IMAGE_FILE = 'SET_RECIPE_IMAGE_FILE';

export const SET_SIGNINUP_MODAL_SHOW = 'SET_SIGNINUP_MODAL_SHOW';

export const SET_INGREDIENT_MODAL_SHOW = 'SET_INGREDIENT_MODAL_SHOW';

export const SET_FRIDGE_MODAL_SHOW = 'SET_FRIDGE_MODAL_SHOW';